### ISSUE TITLE
android: can't execute sample app

### ISSUE THREAD

**Issue by malashkevich** [BlinkID/blinkid-verify-react-native#2]
After creating sample app I get this error:
```
Error:Execution failed for task ':blinkid-verify-react-native:prepareLibPhotoPayLibrary'.
> Could not expand ZIP '/Users/alexei/dev/temp/blinkid-verify-react-native-master/sample/BlinkIDVerifyReactNativeDemo/node_modules/blinkid-verify-react-native/src/android/lib/LibPhotoPay.aar'.
```

Same error when I add this lib to my project.
Am I missing something?

System info:
```
Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2
```

**Comment by lirfu** [comment]
Hi @malashkevich,

have you installed the [dependencies](https://github.com/BlinkID/blinkid-verify-react-native#dependencies). Git LFS is required for Android libraries as well.

Please let us know if this solves your problem.

**Comment by malashkevich** [comment]
Hi @lirfu.
If you mean those .aar files in `./plugin/src/android/lib` then yes, I have them.
Maybe something wrong with those .aar files? Because I also can't unzip them.

**Comment by lirfu** [comment]
Hi @malashkevich,

those files aren't actually downloaded. They are just text representations of them. To actually download the you should execute `git lfs pull`. Read more [here](https://www.atlassian.com/git/tutorials/git-lfs#pulling-and-checking-out).

**Comment by malashkevich** [comment]
Thanks, @lirfu. Seems like the issue was in code downloading approach. I used zip file instead of cloning repo.
