### ISSUE TITLE
android: Application cannot build with google play services

### ISSUE THREAD

**Issue by malashkevich** [BlinkID/blinkid-verify-react-native#3]
Steps to reproduce:
1. init new RN app
2. add `blinkid-verify-react-native`
3. Change `app/build.gradle` to this:
```
dependencies {
    compile project(':blinkid-verify-react-native')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"

    compile "com.google.android.gms:play-services-base:+"
}
```

Expected result: app should build without errors.
Actual result: 
![image](https://user-images.githubusercontent.com/1452064/34374464-4f083f34-eaf2-11e7-838f-1b694ef5fdef.png)

**Comment by lirfu** [comment]
Hi @malashkevich,

please check your library dependencies as mentioned here: https://stackoverflow.com/questions/39347389/attribute-already-defined-with-incompatible-format-original-attribute-defined-h#answer-42578341

**blinkid-verify-react-native** defines appcompat `v25.3.1`: 
https://github.com/BlinkID/blinkid-verify-react-native/blob/master/plugin/src/android/build.gradle#L19

Tell us if this solves your issue!

**Comment by malashkevich** [comment]
Hello @lirfu.
I've created a [reproducible demo](https://github.com/malashkevich/blinktest).
Will you have a chance to look at it and suggest something?

**Comment by lirfu** [comment]
Hi @malashkevich,
the latest [commit](https://github.com/BlinkID/blinkid-verify-react-native/commit/81b07bc06a945e2702ead8b4228750455602674c) updates LibVerification that had a faulty custom attribute definition.

Thank you for your effort!
Please let us know does this solve your issue.

**Comment by malashkevich** [comment]
Thank you @lirfu!
It works.
